import type { GlobalThemeOverrides } from "naive-ui";

export const designTokens = {
  font: {
    sans: 'Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
  },
  color: {
    ink: "#172026",
    textSecondary: "#43525a",
    bodyBg: "#f5f7f8",
    surface: "#ffffff",
    sidebar: "#132126",
    sidebarHover: "#21383f",
    sidebarText: "#f7fbfc",
    sidebarMuted: "#c9d6d9",
    mutedText: "#65747a",
    border: "#dbe3e6",
    borderSubtle: "#e6ecef",
    borderDashed: "#cbd8dd",
    borderHover: "#86b7dd",
    panelTint: "#f9fbfc",
    tableHead: "#f0f5f6",
    actionBlue: "#0f6fbd",
    actionBlueHover: "#0d5f9f",
    actionBluePressed: "#0b4e84",
    operationalTeal: "#137a63",
    operationalTealHover: "#106a58",
    operationalTealPressed: "#0c5748",
    warning: "#9a5b00",
    warningBg: "#fff7e8",
    warningHover: "#824d00",
    warningPressed: "#663c00",
    error: "#b42318",
    errorHover: "#961b12",
    errorPressed: "#7a160f",
    loginBg: "#eef3f5",
    logBg: "#0f171a",
    logText: "#d8e8df",
    codeText: "#263239",
  },
  shadow: {
    panelLift: "0 1px 2px rgb(23 32 38 / 0.04)",
  },
} as const;

const cssVariables: Record<string, string> = {
  "--font-sans": designTokens.font.sans,
  "--font-mono": designTokens.font.mono,
  "--color-ink": designTokens.color.ink,
  "--color-text-secondary": designTokens.color.textSecondary,
  "--color-body-bg": designTokens.color.bodyBg,
  "--color-surface": designTokens.color.surface,
  "--color-sidebar": designTokens.color.sidebar,
  "--color-sidebar-hover": designTokens.color.sidebarHover,
  "--color-sidebar-text": designTokens.color.sidebarText,
  "--color-sidebar-muted": designTokens.color.sidebarMuted,
  "--color-muted-text": designTokens.color.mutedText,
  "--color-border": designTokens.color.border,
  "--color-border-subtle": designTokens.color.borderSubtle,
  "--color-border-dashed": designTokens.color.borderDashed,
  "--color-border-hover": designTokens.color.borderHover,
  "--color-panel-tint": designTokens.color.panelTint,
  "--color-table-head": designTokens.color.tableHead,
  "--color-action-blue": designTokens.color.actionBlue,
  "--color-action-blue-hover": designTokens.color.actionBlueHover,
  "--color-action-blue-pressed": designTokens.color.actionBluePressed,
  "--color-operational-teal": designTokens.color.operationalTeal,
  "--color-operational-teal-hover": designTokens.color.operationalTealHover,
  "--color-operational-teal-pressed": designTokens.color.operationalTealPressed,
  "--color-warning": designTokens.color.warning,
  "--color-warning-bg": designTokens.color.warningBg,
  "--color-warning-hover": designTokens.color.warningHover,
  "--color-warning-pressed": designTokens.color.warningPressed,
  "--color-error": designTokens.color.error,
  "--color-error-hover": designTokens.color.errorHover,
  "--color-error-pressed": designTokens.color.errorPressed,
  "--color-login-bg": designTokens.color.loginBg,
  "--color-log-bg": designTokens.color.logBg,
  "--color-log-text": designTokens.color.logText,
  "--color-code-text": designTokens.color.codeText,
  "--shadow-panel-lift": designTokens.shadow.panelLift,
};

export function applyThemeCssVars(root = document.documentElement): void {
  for (const [name, value] of Object.entries(cssVariables)) {
    root.style.setProperty(name, value);
  }
}

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    baseColor: designTokens.color.surface,
    bodyColor: designTokens.color.bodyBg,
    cardColor: designTokens.color.surface,
    modalColor: designTokens.color.surface,
    tableColor: designTokens.color.surface,
    tableHeaderColor: designTokens.color.tableHead,
    hoverColor: designTokens.color.panelTint,
    inputColor: designTokens.color.surface,
    inputColorDisabled: designTokens.color.panelTint,
    borderColor: designTokens.color.border,
    dividerColor: designTokens.color.borderSubtle,
    primaryColor: designTokens.color.operationalTeal,
    primaryColorHover: designTokens.color.operationalTealHover,
    primaryColorPressed: designTokens.color.operationalTealPressed,
    primaryColorSuppl: designTokens.color.operationalTeal,
    infoColor: designTokens.color.actionBlue,
    infoColorHover: designTokens.color.actionBlueHover,
    infoColorPressed: designTokens.color.actionBluePressed,
    infoColorSuppl: designTokens.color.actionBlue,
    successColor: designTokens.color.operationalTeal,
    successColorHover: designTokens.color.operationalTealHover,
    successColorPressed: designTokens.color.operationalTealPressed,
    successColorSuppl: designTokens.color.operationalTeal,
    warningColor: designTokens.color.warning,
    warningColorHover: designTokens.color.warningHover,
    warningColorPressed: designTokens.color.warningPressed,
    warningColorSuppl: designTokens.color.warning,
    errorColor: designTokens.color.error,
    errorColorHover: designTokens.color.errorHover,
    errorColorPressed: designTokens.color.errorPressed,
    errorColorSuppl: designTokens.color.error,
    textColorBase: designTokens.color.ink,
    textColor1: designTokens.color.ink,
    textColor2: designTokens.color.textSecondary,
    textColor3: designTokens.color.mutedText,
    textColorDisabled: designTokens.color.mutedText,
    placeholderColor: designTokens.color.mutedText,
    placeholderColorDisabled: designTokens.color.mutedText,
    iconColor: designTokens.color.mutedText,
    fontFamily: designTokens.font.sans,
    fontFamilyMono: designTokens.font.mono,
    fontSize: "16px",
    borderRadius: "7px",
    borderRadiusSmall: "7px",
  },
};
